server:
  port: 9802
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: VipApi
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://47.96.230.209:8080/eureka/eureka/