spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://47.96.230.209:8080/eureka/eureka/
#mybatis:
#  mapper-locations: classpath*:/mapper/*.xml
