spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.230.209:3306/springRead?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://47.96.230.209:8080/eureka/eureka/
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
